@baseUrl = http://localhost:5001/api/

### GET PROFILE
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2huZG9lQHRlc3QuY29tIiwianRpIjoiYzM3Zjk2M2EtMDRlMy00ZmE0LTlhMzQtOTYwMDFjYzdlMmFmIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc0NjYxODkzOCwiaXNzIjoiQXV0aEp3dElzc3VlciIsImF1ZCI6IkF1dGhKd3RBdWRpZW5jZSJ9.36KKQtQhPuuM0m19BErqdeqE0isFIxERtNwPlsGXqhU

GET {{baseUrl}}/account/profile
Authorization: Bearer {{accessToken}}